### ISSUE TITLE
conflicting types

### ISSUE THREAD

**Issue by stalker37** [huskyproject/hptzip#6]
[stalker@f37 hptzip]$ make
gcc -c -s -O3 -fomit-frame-pointer -fstrength-reduce -fPIC -Ihptzip -I/usr/local/ftn/include -Wall -DUNIX -DUNAME=\"LNX\"  src/hptzip.c
In file included from /usr/include/features.h:368:0,
                 from /usr/include/stdio.h:27,
                 from src/hptzip.c:12:
/usr/include/sys/stat.h:501:1: error: conflicting types for ‘stat64’
 __NTH (stat64 (const char *__path, struct stat64 *__statbuf))
 ^
In file included from /usr/local/ftn/include/huskylib/compiler.h:1286:0,
                 from /usr/local/ftn/include/huskylib/huskyext.h:15,
                 from src/hptzip.c:37:
/usr/include/sys/stat.h:227:12: note: previous declaration of ‘stat64’ was here
 extern int stat64 (const char *__restrict __file,
            ^
In file included from /usr/include/features.h:368:0,
                 from /usr/include/stdio.h:27,
                 from src/hptzip.c:12:
/usr/include/sys/stat.h:508:1: error: conflicting types for ‘lstat64’
 __NTH (lstat64 (const char *__path, struct stat64 *__statbuf))

**Comment by dukelsky** [comment]
Fixed.
